### ISSUE TITLE
Accidental scroll jumps because of bubble width touch area on whole height

### ISSUE THREAD

**Issue by tschweitzer** [L4Digital/FastScroll#80]
It seems that while the bubble is visible the whole vertical area (pink rectangle on screenshot) is tappable and when tapping in that area (pink circle on the screenshot) the bubble jumps to that position and with that scrolls far away from the current position.

The wider the bubble is the wider is that tappable area and accidental jumps happen easy. Would it be possible to only allow dragging the bubble (green rectangle area on screenshot) instead of making the whole vertical area tappable?
![bubble_area](https://user-images.githubusercontent.com/883813/159041760-23d13579-b6e6-4f77-8d5e-68d37612f4c3.jpg)

**Comment by randr0id** [comment]
Thanks for the feedback.

Tapping above or below the current position to quickly jump to a new position is an intended feature. However, I can see that capturing tap events for the whole view could lead to errant scrolling, especially if the bubble is always visible.

I will update so that only tapping above or below the handle will jump to that position and the bubble only allows dragging to scroll.

**Comment by randr0id** [comment]
Addressed by #85 and will be released in 3.0.0-beta3
